-- MySQL Script generated by MySQL Workbench
-- Sat Sep 19 21:15:25 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema KalenikDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema KalenikDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `KalenikDB` DEFAULT CHARACTER SET utf8 ;
USE `KalenikDB` ;

-- -----------------------------------------------------
-- Table `KalenikDB`.`TestTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KalenikDB`.`TestTable` (
  `idTestTable` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(20) NOT NULL,
  `Surname` VARCHAR(20) NOT NULL,
  `Age` INT NOT NULL,
  PRIMARY KEY (`idTestTable`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `KalenikDB`.`TestTable`
-- -----------------------------------------------------
START TRANSACTION;
USE `KalenikDB`;
INSERT INTO `KalenikDB`.`TestTable` (`idTestTable`, `Name`, `Surname`, `Age`) VALUES (1, 'Dima', 'Surname1', 18);
INSERT INTO `KalenikDB`.`TestTable` (`idTestTable`, `Name`, `Surname`, `Age`) VALUES (2, 'Dima', 'Surname2', 17);
INSERT INTO `KalenikDB`.`TestTable` (`idTestTable`, `Name`, `Surname`, `Age`) VALUES (3, 'Ivan', 'Surname3', 16);
INSERT INTO `KalenikDB`.`TestTable` (`idTestTable`, `Name`, `Surname`, `Age`) VALUES (4, 'Ivan', 'Surname4', 15);
INSERT INTO `KalenikDB`.`TestTable` (`idTestTable`, `Name`, `Surname`, `Age`) VALUES (5, 'Denis', 'Surname5', 14);
INSERT INTO `KalenikDB`.`TestTable` (`idTestTable`, `Name`, `Surname`, `Age`) VALUES (6, 'Denis', 'Surname6', 13);
INSERT INTO `KalenikDB`.`TestTable` (`idTestTable`, `Name`, `Surname`, `Age`) VALUES (7, 'Nikita', 'Surname7', 12);
INSERT INTO `KalenikDB`.`TestTable` (`idTestTable`, `Name`, `Surname`, `Age`) VALUES (8, 'Nikita', 'Surname8', 11);
INSERT INTO `KalenikDB`.`TestTable` (`idTestTable`, `Name`, `Surname`, `Age`) VALUES (9, 'Ilya', 'Surname9', 10);
INSERT INTO `KalenikDB`.`TestTable` (`idTestTable`, `Name`, `Surname`, `Age`) VALUES (10, 'Ilya', 'Surname10', 9);

COMMIT;

